import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { ComplianceRequirement, Project } from '../../entities/entities';
import * as puppeteer from 'puppeteer';
import * as Handlebars from 'handlebars';

const complianceMatrixTemplate = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
body{font-family:Arial,sans-serif;margin:20px;color:#0f172a}
h1{color:#1e40af;margin-bottom:4px}
.project-meta{color:#64748b;font-size:13px;margin-bottom:24px}
table{width:100%;border-collapse:collapse;font-size:12px}
th{background:#1e40af;color:#fff;padding:10px 8px;text-align:left;font-weight:600}
td{padding:8px;border-bottom:1px solid #e2e8f0}
.status-badge{display:inline-block;padding:2px 10px;border-radius:12px;font-size:11px;font-weight:600}
.met{background:#dcfce7;color:#166534}
.missing{background:#fee2e2;color:#991b1b}
.needs_review{background:#fef9c3;color:#854d0e}
.footer{text-align:center;margin-top:32px;font-size:11px;color:#94a3b8}
</style></head><body>
<h1>Compliance Matrix</h1>
<div class="project-meta">
  <strong>Project:</strong> {{project.name}} | 
  <strong>Client:</strong> {{project.client}} | 
  <strong>Status:</strong> {{project.status}} | 
  <strong>Generated:</strong> {{generatedAt}}
</div>
<table>
<thead><tr>
  <th>Section</th><th>Category</th><th>Requirement</th><th>Severity</th><th>Status</th><th>Evidence</th>
</tr></thead>
<tbody>
{{#each requirements}}
<tr>
  <td>{{this.sectionRef}}</td>
  <td>{{this.category}}</td>
  <td>{{this.requirementText}}</td>
  <td>{{this.severity}}</td>
  <td><span class="status-badge {{this.status}}">{{this.status}}</span></td>
  <td>{{this.evidence}}</td>
</tr>
{{/each}}
</tbody>
</table>
<div class="footer">Generated by RFPilot AI-Powered Proposal Engine</div>
</body></html>`;

@Injectable()
export class ComplianceExportService {
  constructor(
    @InjectRepository(Project) private projectRepo: Repository<Project>,
    @InjectRepository(ComplianceRequirement) private reqRepo: Repository<ComplianceRequirement>,
  ) {}

  async generateMatrixPdf(projectId: string): Promise<Buffer> {
    const project = await this.projectRepo.findOne({ where: { id: projectId } });
    if (!project) throw new Error('Project not found');

    const requirements = await this.reqRepo.find({ where: { projectId } });
    const template = Handlebars.compile(complianceMatrixTemplate);
    const html = template({
      project,
      requirements,
      generatedAt: new Date().toISOString(),
    });

    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
      executablePath: process.env.PUPPETEER_EXECUTABLE_PATH,
    });
    try {
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0' });
      const pdf = await page.pdf({ format: 'A4', landscape: true, margin: { top: '20px', bottom: '20px' } });
      return Buffer.from(pdf);
    } finally {
      await browser.close();
    }
  }
}
