import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  PORT: Joi.number().default(3000),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().default(5432),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_DATABASE: Joi.string().required(),
  DB_SSL: Joi.boolean().default(false),
  DB_POOL_MIN: Joi.number().default(2),
  DB_POOL_MAX: Joi.number().default(10),
  DB_READ_HOST: Joi.string().optional(),
  DB_READ_PORT: Joi.number().optional(),
  DB_READ_USERNAME: Joi.string().optional(),
  DB_READ_PASSWORD: Joi.string().optional(),
  DB_READ_DATABASE: Joi.string().optional(),
  REDIS_HOST: Joi.string().required(),
  REDIS_PORT: Joi.number().default(6379),
  REDIS_PASSWORD: Joi.string().allow('').optional(),
  REDIS_DB: Joi.number().default(0),
  S3_ENDPOINT: Joi.string().required(),
  S3_REGION: Joi.string().default('us-east-1'),
  S3_ACCESS_KEY: Joi.string().required(),
  S3_SECRET_KEY: Joi.string().required(),
  S3_BUCKET: Joi.string().required(),
  S3_USE_PATH_STYLE: Joi.boolean().default(false),
  S3_CDN_URL: Joi.string().optional().allow(''),
  OPENAI_API_KEY: Joi.string().required(),
  OPENAI_MODEL: Joi.string().default('gpt-4o'),
  OPENAI_EMBEDDING_MODEL: Joi.string().default('text-embedding-3-small'),
  ANTHROPIC_API_KEY: Joi.string().optional(),
  ANTHROPIC_MODEL: Joi.string().default('claude-3-5-sonnet-20241022'),
  UNSTRUCTURED_API_KEY: Joi.string().optional(),
  UNSTRUCTURED_API_URL: Joi.string().default('https://api.unstructured.io/general/v0/general'),
  TIKA_URL: Joi.string().optional(),
  CLERK_JWKS_URL: Joi.string().required(),
  CLERK_ISSUER: Joi.string().required(),
  CLERK_SECRET_KEY: Joi.string().optional(),
  STRIPE_SECRET_KEY: Joi.string().required(),
  STRIPE_WEBHOOK_SECRET: Joi.string().required(),
  STRIPE_PRICE_IDS: Joi.string().required(),
  SENDGRID_API_KEY: Joi.string().optional(),
  FROM_EMAIL: Joi.string().default('noreply@rfpilot.io'),
  APP_URL: Joi.string().default('http://localhost:3000'),
  FRONTEND_URL: Joi.string().default('http://localhost:5173'),
  LOG_LEVEL: Joi.string().valid('error', 'warn', 'info', 'debug').default('info'),
  CIRCUIT_BREAKER_THRESHOLD: Joi.number().default(5),
  CIRCUIT_BREAKER_TIMEOUT: Joi.number().default(30000),
  RATE_LIMIT_TTL: Joi.number().default(60),
  RATE_LIMIT_MAX: Joi.number().default(100),
  SENTRY_DSN: Joi.string().optional(),
  PROMETHEUS_METRICS: Joi.boolean().default(true),
  METRICS_TOKEN: Joi.string().min(16).when('NODE_ENV', {
    is: 'production',
    then: Joi.required(),
    otherwise: Joi.optional(),
  }),
  ENCRYPTION_KEY: Joi.string().length(64).when('NODE_ENV', {
    is: 'production',
    then: Joi.required(),
    otherwise: Joi.optional(),
  }),
  POSTHOG_API_KEY: Joi.string().optional(),
  POSTHOG_HOST: Joi.string().default('https://app.posthog.com'),
  FEATURE_FLAGS: Joi.string().optional().default(''),
  ADMIN_JWT_SECRET: Joi.string().optional(),
  ADMIN_SESSION_TIMEOUT: Joi.number().default(3600000),
  ADMIN_TOTP_ISSUER: Joi.string().default('RFPilot'),
  REFERRAL_CREDIT_AMOUNT: Joi.number().default(50),
  TRIAL_LENGTH_DAYS: Joi.number().default(14),
  SAM_GOV_API_KEY: Joi.string().optional(),
  SAM_GOV_BASE_URL: Joi.string().default('https://api.sam.gov/opportunities/v2'),
});
